# fly.toml app configuration file generated for ppob-fake-api on 2024-08-25T15:10:26+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ppob-fake-api'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
